### ISSUE TITLE
Unable to build on Solaris 11.4

### ISSUE THREAD

**Issue by m4r1k** [hishamhm/htop#873]
Hey there,

I've tried to build htop on Solaris 11.4 but it fails in the early make phases.

```sh
CRT.h:113:4: error: expected identifier before numeric constant
    CPU_KERNEL,
    ^
In file included from ColumnsPanel.c:13:0:
CRT.h:145:47: error: ‘LAST_COLORELEMENT’ undeclared here (not in a function); did you mean ‘LAST_COLORSCHEME’?
 extern int CRT_colorSchemes[LAST_COLORSCHEME][LAST_COLORELEMENT];
                                               ^~~~~~~~~~~~~~~~~
                                               LAST_COLORSCHEME
```

Follows the full log
https://pastebin.com/xt2VbccD

Did I do something wrong?

Thanks!

**Comment by ninefathom** [comment]
Found the issue.  Solaris 11.4 now includes <sys/sysinfo.h> from <sys/zone.h>.  Previous Solaris versions did not, and illumos still does not.  That inclusion is causing a macro name collission with htop.  I've have a PR to fix this at some point in the next day or two.

In the mean time, please try my solaris-114_fixup branch from https://github.com/ninefathom/htop and let me know if that takes care of it.

**Comment by m4r1k** [comment]
Hey ninefathom,

Thanks for the quick reply.
I've tested the branch solaris-114_fixup and make fails at the same point.

```sh
In file included from /usr/include/sys/zone.h:28:0,
                 from /usr/include/sys/corectl.h:9,
                 from /usr/include/libproc.h:36,
                 from ./solaris/Platform.h:20,
                 from ColumnsPanel.c:9:
CRT.h:113:4: error: expected identifier before numeric constant
    CPU_KERNEL,
    ^
In file included from ColumnsPanel.c:13:0:
CRT.h:145:47: error: ‘LAST_COLORELEMENT’ undeclared here (not in a function); did you mean ‘LAST_COLORSCHEME’?
 extern int CRT_colorSchemes[LAST_COLORSCHEME][LAST_COLORELEMENT];
                                               ^~~~~~~~~~~~~~~~~
                                               LAST_COLORSCHEME
*** Error code 1
make: Fatal error: Command failed for target `ColumnsPanel.o'
```

**Comment by ninefathom** [comment]
@m4r1k Whoops.  Made a change but forgot to push - dangers of coding while half asleep.  Please do a "git pull" and try again.

**Comment by m4r1k** [comment]
Yup now it works like a charm!

**Comment by ninefathom** [comment]
Wonderful.  Thank you for testing.  I'll have to put a bit more thought into how I want to fix the issue upstream, so a PR in the main htop repo might be a few days out yet.  In the mean time, if you're new to htop on Solaris, you should find that it's stable, and the data is generally consistent with that of prstat.  Notable exceptions: memory usage graphs are for the entire system, rather than for the given zone (if applicable), and each process's CPU time shows the time for the master thread, rather than the cumulative time for all threads in the process.  Still working on both of those issues.

**Comment by m4r1k** [comment]
> Wonderful. Thank you for testing. I'll have to put a bit more thought into how I want to fix the issue upstream, so a PR in the main htop repo might be a few days out yet. In the mean time, if you're new to htop on Solaris, you should find that it's stable, and the data is generally consistent with that of prstat. Notable exceptions: memory usage graphs are for the entire system, rather than for the given zone (if applicable)

To me, this is not just common to Solaris htop but in general to HTOP design.
htop classify memory as used, buffers, and cache. This is fundamentally wrong since every major platform organizes and classify memory in very different ways. This looks very Linux old-school centric.

> and each process's CPU time shows the time for the master thread, rather than the cumulative time for all threads in the process. Still working on both of those issues.

Oh... I just noticed that. Initially, I thought you meant the difference in CPU report between Linux and Solaris (well, UNIX) TOP. But then I noticed all my threads have the same CPU consumption.

I don't know which strategy you're going to adopt but consistent to the platform would be per thread related to all the CPUs available. Linux is still per thread and related to the CPU where the process is executed (aka 100% means one cpu fully utilized, while 100% in Solaris means the whole system utilized)

**Comment by ninefathom** [comment]
PR #875 submitted, which not only fixes this specific issue on Solaris, but should also help to avoid similar problems on other platforms going forward.  Thanks, @m4r1k !

**Comment by ninefathom** [comment]
PR #875 cancelled.  PR #876 created, which contains some additional fixes and improvements.

**Comment by yanryb** [comment]
Hi

I have this problem on my Solaris 11.4 to.
Something I is missing, I am using your git repo...

/Y
