### ISSUE TITLE
Build fails on OS X 10.12

### ISSUE THREAD

**Issue by sbrenner** [hishamhm/htop#668]
I am trying to compile on OS X 10.12 and I am getting the following error:

ziva:htop sbrenner$ make
/Applications/Xcode-beta.app/Contents/Developer/usr/bin/make  all-am
gcc -DHAVE_CONFIG_H -I.  -DNDEBUG  -pedantic -Wall -Wextra -std=c99 -D_XOPEN_SOURCE_EXTENDED -DSYSCONFDIR=\"/usr/local/etc\" -I"./darwin"  -g -O2 -MT htop-AvailableMetersPanel.o -MD -MP -MF .deps/htop-AvailableMetersPanel.Tpo -c -o htop-AvailableMetersPanel.o `test -f 'AvailableMetersPanel.c' || echo './'`AvailableMetersPanel.c
In file included from AvailableMetersPanel.c:8:
In file included from ./AvailableMetersPanel.h:12:
In file included from ./Settings.h:14:
In file included from ./Process.h:24:
In file included from ./Object.h:13:
In file included from ./XAlloc.h:10:
/usr/local/include/err.h:378:7: error: unknown type name 'ERR_FNS'
const ERR_FNS *ERR_get_implementation(void);
      ^
/usr/local/include/err.h:383:34: error: unknown type name 'ERR_FNS'
int ERR_set_implementation(const ERR_FNS *fns);
                                 ^
AvailableMetersPanel.c:130:10: warning: implicit declaration of function 'err' is invalid in C99 [-Wimplicit-function-declaration]
         xSnprintf(buffer, 50, "%s %d", type->uiName, i);
         ^
./XAlloc.h:20:142: note: expanded from macro 'xSnprintf'
  ...do { int _l=len; int _n=snprintf(fmt, _l, __VA_ARGS__); if (!(_n > -1 && _n < _l)) { curs_set(1); endwin(); err(1, NULL); } } while(0)
                                                                                                                 ^
1 warning and 2 errors generated.
make[1]: *** [htop-AvailableMetersPanel.o] Error 1
make: *** [all] Error 2

I'm not sure how to go about troubleshooting, so please let me know if I can provide any additional info.

Thanks, Scott

**Comment by edrozenberg** [comment]
I've got 2.0.2 installed with homebrew on macOS 10.12.6 (16G29), works fine.

Install homebrew: https://brew.sh

Then:
```
$ brew install ncurses
$ brew install --with-ncurses htop
```
