### ISSUE TITLE
Build failure of htop 3.0.0beta5 on FreeBSD

### ISSUE THREAD

**Issue by dmilith** [hishamhm/htop#1023]
```
Settings.c:220:21: error: use of undeclared identifier 'LAST_PROCESSFIELD'; did you mean 'NULL_PROCESSFIELD'?
   if (i < 0 || i > LAST_PROCESSFIELD) {
                    ^~~~~~~~~~~~~~~~~
                    NULL_PROCESSFIELD
./Process.h:37:4: note: 'NULL_PROCESSFIELD' declared here
   NULL_PROCESSFIELD = 0,
   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
2 errors generated.
```

System: FreeBSD 12.1, x86_64
Htop: 3.0.0beta5

**Comment by natoscott** [comment]
@dmilith you'd be better off working on the master branch - the 3.0.0beta branches are long out of date.

Does the build still fail there?  It looks like that symbol *is* defined for FreeBSD, so if it still fails its likely a missing #include issue I guess.

**Comment by gaod** [comment]
https://github.com/gaod/htop/commit/441fad01b87f8fd6f378cb2ff6b207bf44992067

Take a look?

**Comment by dmilith** [comment]
Is it normal that produced build from master shows version 2.2.0 or I did something wrong? But I think it builds just fine :)
