### ISSUE TITLE
compile error mac

### ISSUE THREAD

**Issue by kaefer** [hishamhm/htop#271]
Hi, 
compiling the latest source with OS X 10.9.1 (i know..old system..) fails with this message: 
`darwin/DarwinProcessList.c:17:10: fatal error: 'mach/vm_page_size.h' file not found`

changing this line in DarwinProcessList.c
```
-#include <mach/vm_page_size.h>
+#include <mach/mach.h>
```
is working. However I don't know whether this is appropriate or not (don't know much about C).

**Comment by hishamhm** [comment]
Thanks for the info... it would be good to check this with other Mac users.
@jweyrich, what version are you compiling with? Does the above change work in your system?

**Comment by jweyrich** [comment]
The proposed change works on 10.10.5 as well. My intuition says it should work with all XNU versions since `mach/mach.h` is the main XNU header - it includes all types that a userspace application should need.

**Comment by kaefer** [comment]
```
$ uname -v
Darwin Kernel Version 13.0.0: Thu Sep 19 22:22:27 PDT 2013; root:xnu-2422.1.72~6/RELEASE_X86_64
```
fooling around with the code, I found you can remove this include as htop works without because `vm_page_size` is already set without this include (already included somewhere else?).

**Comment by jweyrich** [comment]
I see `DarwinProcessList.h` already includes `mach/mach_host.h`, so you're right, the implementation file doesn't need to include anything else. We might want to include `mach/mach.h` instead (not sure, but it already includes `mach_host.h` itself) - don't have much experience with the kernel :-(

**Comment by kaefer** [comment]
I don't think we have to include `mach/mach.h` instead of `mach/mach_host.h` if `mach/mach_host.h` is  sufficient for this code.

**Comment by kaefer** [comment]
just did the code change. - i simply added a commit to #273 as both changes are mac/darwin related.

**Comment by kaefer** [comment]
closed, this is merged with #273
