### ISSUE TITLE
Build failure on Solaris 11.3 (and subsequent fix)

### ISSUE THREAD

**Issue by tofurky** [hishamhm/htop#908]
I've got a SPARC T3-1 here running Solaris 11.3 and was pleased to see that htop recently added support.

However, a hard dependency on `libproc.h` as was introduced in 45fad05b4a99c016a12fe7875ea749316283df49 causes build failures on 11.3 due to the OS not shipping or otherwise making that header available. I was able to download this header (https://github.com/sucode/onnv-gate/blob/master/usr/src/lib/libproc/common/libproc.h) from a mirror of an old OpenSolaris release and place it in /usr/include to get further into the build process.

I then ran into another build issue due to `CPU_KERNEL` as is defined in the ColorElements enum in `CRT.h`. The chain of headers brought in include a definition of `CPU_KERNEL` in `/usr/include/sys/sysinfo.h`, causing a build failure like so:
```
In file included from /usr/include/sys/zone.h:27:0,
                 from /usr/include/sys/corectl.h:9,
                 from /usr/include/libproc.h:64,
                 from ./solaris/Platform.h:20,
                 from ColumnsPanel.c:9:
CRT.h:115:4: error: expected identifier before numeric constant
    CPU_KERNEL,
    ^
In file included from ColumnsPanel.c:13:0:
CRT.h:147:47: error: ‘LAST_COLORELEMENT’ undeclared here (not in a function); did you mean ‘LAST_COLORSCHEME’?
 extern int CRT_colorSchemes[LAST_COLORSCHEME][LAST_COLORELEMENT];
                                               ^~~~~~~~~~~~~~~~~
                                               LAST_COLORSCHEME
```
Adding `#undef CPU_KERNEL` towards the top of `CRT.h` fixed that build issue and htop then successfully builds and runs on Solaris 11.3.

Would there be a possibility of including `libproc.h` in the solaris/ directory or similar? And if so, could a conditional `#undef CPU_KERNEL` be added to `CRT.h`?

Thanks!
